---
- hosts: all
  become: yes

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted

  tasks: 
        - name: apache2
          apt: name=apache2 state=present

        - name: service start
          service: name=apache2 state=started enabled=yes

        - name: service stopped
          service: name=apache2 state=stopped enabled=no"

  notify:
           - restart apache2

... 
